---
- name: Run solana task
  ansible.builtin.import_tasks: darwin.yaml
  when: ansible_system == 'Darwin'

- name: Run solana task
  ansible.builtin.import_tasks: linux.yml
  when: ansible_system == 'Linux'
