---
- name: Check if baba_coiffure monorepo exists
  ansible.builtin.stat:
    path: ~/coding/work/
  register: baba_monorepo_exists

- name: clone baba_coiffure repo
  ansible.builtin.git:
    clone: true
    repo: git@github.com:babacoiffure/babacoiffure_monorepo.git
    dest: ~/coding/work/
    update: false
    bare: true
  when: not baba_monorepo_exists.stat.exists

- name: Check if baba_coiffure landing exists
  ansible.builtin.stat:
    path: ~/coding/work/baba_coiffure
  register: baba_landing_exists

- name: clone baba_coiffure repo
  ansible.builtin.git:
    clone: true
    repo: git@github.com:babacoiffure/landing.git
    dest: ~/coding/work/landing
    update: false
    bare: true
  when: not baba_landing_exists.stat.exists
