---
- name: Check if backup repo exists
  ansible.builtin.stat:
    path: ~/backup
  register: backup_exists

- name: BACKUP
  ansible.builtin.git:
    version: main
    repo: git@github.com:G33KM44N38/backup.git
    update: false
    dest: ~/backup
  when: not backup_exists.stat.exists
