default_roles:
     - nvim
     - go
     - stow
     - lazygit
     - lazydocker
     - ripgrep
     - tmux
     # - skhd
     # - yabai
     - node
     - fzf
     # - cmake
     - stripe
     # - z
     # - gh
     # - qmk
     - shortcat
     # aldente
     # - scw
     - dir
     - appcleaner
     - raycast
     - nerd_font
     - arc
     - work
     - zsh
     # - age
     - dock
     - figma
     - karabiner
     - yarn
     # - gitspeak
     - aerospace
     - python
       - arc-cli
       - pnpm
     - ghostty
     - cron
     - mouseless
     - backup
     - discord
     - rust
       - beeper
       - notion
     - lua-language-server
     - config
     - fd
